const menu = [
  {
    id: 1,
    title: 'dosa',
    category: 'breakfast',
    price: 20,
    img: './images/dosa.jpg',
    desc: `I'm baby woke mlkshk wolf bitters live-edge blue bottle, hammock freegan copper mug whatever cold-pressed `,
  },
  {
    id: 2,
    title: 'sambar',
    category: 'lunch',
    price: 60,
    img: './images/sambar.jpg',
    desc: `vaporware iPhone mumblecore selvage raw denim slow-carb leggings gochujang helvetica man braid jianbing. Marfa thundercats `,
  },
  {
    id: 3,
    title: 'chicken Briyani',
    category: 'briyani',
    price: 90,
    img: './images/briyani.jpg',
    desc: `ombucha chillwave fanny pack 3 wolf moon street art photo booth before they sold out organic viral.`,
  },
  {
    id: 4,
    title: 'idli',
    category: 'breakfast',
    price: 20,
    img: './images/idli.jpg',
    desc: `Shabby chic keffiyeh neutra snackwave pork belly shoreditch. Prism austin mlkshk truffaut, `,
  },
  {
    id: 5,
    title: 'curd rice',
    category: 'lunch',
    price: 40,
    img: './images/curdrice.jpg',
    desc: `franzen vegan pabst bicycle rights kickstarter pinterest meditation farm-to-table 90's pop-up `,
  },
  {
    id: 6,
    title: 'chappathi',
    category: 'dinner',
    price: 25,
    img: './images/chappathi.jpg',
    desc: `Portland chicharrones ethical edison bulb, palo santo craft beer chia heirloom iPhone everyday`,
  },
  {
    id: 7,
    title: 'pongal',
    category: 'breakfast',
    price: 50,
    img: './images/pongal.jpg',
    desc: `carry jianbing normcore freegan. Viral single-origin coffee live-edge, pork belly cloud bread iceland put a bird `,
  },
  {
    id: 8,
    title: 'fried rice',
    category: 'lunch',
    price: 60,
    img: './images/friedrice.jpg',
    desc: `on it tumblr kickstarter thundercats migas everyday carry squid palo santo leggings. Food truck truffaut  `,
  },
  {
    id: 9,
    title: 'snacks',
    category: 'snacks',
    price: 30,
    img: './images/snacks.jpg',
    desc: `skateboard fam synth authentic semiotics. Live-edge lyft af, edison bulb yuccie crucifix microdosing.`,
  },
];
export default menu;
